### PR TITLE
filling out missing params in objects returned from list

### PR DESCRIPTION
**Pull request by soldair**
i made a pr to the original but he said your's was better. =)

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Ideally we merge again. Hes got the history and name share and the code
came from him :) @garrows

**Comment by garrows** [comment]
Hey @jacobrosenthal. 
I've really dropped the ball on my repo so I've given you access to it :) 
Once everything is synced up I'll add you to the NPM collaborators list so you can publish too. 
Thanks for being awesome!

**Comment by jacobrosenthal** [comment]
NP. we ended up iterating really fast at robots conf. I cant keep up with
single PRs on my random repos :)

What should we do, just rebase off my head?

**Comment by phated** [comment]
I would think a single PR would be fine. There were no tests or anything and the changes we made at RC were quite sweeping.

**Comment by garrows** [comment]
Single PR sounds good. Here is one that @jacobrosenthal prepaired earlier https://github.com/garrows/browser-serialport/pull/15#issuecomment-69527083

**Pull request merged**
